<?php
/*
 * This file is a part of package t-co-labs/laravel-marking
 *
 * (c) T.Labs & Co.
 * Contact for Work: T. <hongty.huynh@gmail.com>
 *
 * Got a PHP or Laravel project? We're your go-to team! We can help you:
 *   - Architect the perfect solution for your specific needs.
 *   - Get cleaner, faster, and more efficient code.
 *   - Boost your app's performance through refactoring and optimization.
 *   - Build your project the right way with Laravel best practices.
 *   - Get expert guidance and support for all things Laravel.
 *   - Ensure high-quality code through thorough reviews.
 *   - Provide leadership for your team and manage your projects effectively.
 *   - Bring in a seasoned Technical Lead.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
namespace TLabsCo\LaravelMarking;

use Closure;
use Spatie\LaravelPackageTools\Package;
use Spatie\LaravelPackageTools\PackageServiceProvider;
use TLabsCo\LaravelMarking\Commands\MarkingCommand;

class MarkingServiceProvider extends PackageServiceProvider
{
    public function configurePackage(Package $package): void
    {
        /*
         * This class is a Package Service Provider
         *
         * More info: https://github.com/spatie/laravel-package-tools
         */
        $package
            ->name('laravel-marking')
            ->hasConfigFile('marking')
            ->hasMigration('create_laravel_marking_table')
            ->hasCommand(MarkingCommand::class);
    }

    public function booted(Closure $callback)
    {
        parent::booted($callback); // TODO: Change the autogenerated stub

        $this->mergeConfigFrom(
            __DIR__.'/../config/marking.php', 'marking'
        );

        $this->publishes([
            __DIR__.'/../database/migrations/' => database_path('migrations/create_laravel_marking_table'),
        ], 'laravel-marking-migrations');
    }
}
